# Configuration used for dependency checking with cargo-deny.
#
# For further details on all configuration options see:
# https://embarkstudios.github.io/cargo-deny/checks/cfg.html
[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

# Deny all advisories unless explicitly ignored.
[advisories]
yanked = "deny"
ignore = [
    # Remove once chrono has been updated to pull in a fixed version of time.
    # See https://github.com/chronotope/chrono/issues/553
    "RUSTSEC-2020-0071",
    # atty is not used with a custom global allocator.
    "RUSTSEC-2021-0145",
    # rusoto_* is Unmaintained.
    # TODO(#416): migrate off rusoto
    "RUSTSEC-2022-0071",
    # ansi_term is Unmaintained (via structopt(0.3.26)).
    "RUSTSEC-2021-0139",
    # No use of externally-provided WebPKI chains.
    "RUSTSEC-2023-0052",
    # No use of X.509.
    "RUSTSEC-2023-0072",
]

# Deny multiple versions unless explicitly skipped.
[bans]
multiple-versions = "deny"
wildcards = "allow"

######################################

# Old versions of crates pulled in (transitively) by rusoto_*(v0.47.0)
[[bans.skip]]
name = "hmac"
version = "=0.11.0"
[[bans.skip]]
name = "base64"
version = "=0.13.1"
[[bans.skip]]
name = "digest"
version = "0.9.0"
[[bans.skip]]
name = "sha2"
version = "0.9.9"

# structopt(0.3.26) => structopt-derive(0.4.18) => heck(0.3.*)
[[bans.skip]]
name = "heck"
version = "0.3.1"

# tower(0.4.13) => indexmap(1.9.3) => hashbrown(0.12.3)
[[bans.skip]]
name = "indexmap"
version = "1.9.3"
[[bans.skip]]
name = "hashbrown"
version = "0.12.3"

# Various dependencies use earlier versions of windows-sys and its deps
[[bans.skip]]
name = "windows-sys"
version = "0.45.0"
[[bans.skip]]
name = "windows-sys"
version = "0.42.0"
[[bans.skip]]
name = "windows-targets"
version = "0.42.1"
[[bans.skip]]
name = "windows_x86_64_msvc"
version = "0.42.1"

# Various dependencies use block-buffer(0.9.0)
[[bans.skip]]
name = "block-buffer"
version = "0.9.0"

# Various dependencies use syn(1.0.109)
[[bans.skip]]
name = "syn"
version = "1.0.109"

######################################

# List of allowed licenses.
# For more detailed information see http://go/thirdpartylicenses.
[licenses]
allow = [
  "Apache-2.0",
  "ISC",
  "MIT",
  "OpenSSL",
  "BSD-3-Clause",
  "Unicode-DFS-2016",
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 3171872035 }]
