# Configuration used for dependency checking with cargo-deny.
#
# For further details on all configuration options see:
# https://embarkstudios.github.io/cargo-deny/checks/cfg.html
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

# Deny all advisories unless explicitly ignored.
[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
  # TODO: Remove when mio no longer depends on net2.
  "RUSTSEC-2020-0016",
  # TODO: Remove when rusoto-* no longer depends on dirs.
  "RUSTSEC-2020-0053",
]

# Deny multiple versions unless explicitly skipped.
[bans]
multiple-versions = "deny"
wildcards = "allow"

# rusoto_*(v0.45.0) => hmac(v0.8.x) => crypto-mac(v0.8.x)
[[bans.skip]]
name = "crypto-mac"
version = "=0.8.0"
[[bans.skip]]
name = "hmac"
version = "0.8.1"

# tokio(v0.2.22) => mio-named-pipes(v0.1.7) => {miow (v0.3.5), mio (v0.6.22) => miow (v0.2.2)}
[[bans.skip]]
name = "miow"
version = "=0.2.1"

# rusoto_*(v0.45.0) => pin-project-*(v0.4.x)
[[bans.skip]]
name = "pin-project"
version = "=0.4.26"
[[bans.skip]]
name = "pin-project-internal"
version = "=0.4.26"

# rusoto_*(v0.45.0) => chrono(v0.4.x) => time(>=v0.1.43,<0.2.0)
[[bans.skip]]
name = "time"
version = "=0.1.44"

# mio (v0.6.22) => kernel32-sys (v0.2.2) => winapi (v0.2.8)
# (many crates) => winapi (v0.3.9)
[[bans.skip]]
name = "winapi"
version = "=0.2.8"

# List of allowed licenses.
# For more detailed information see http://go/thirdpartylicenses.
[licenses]
allow = ["Apache-2.0", "MIT", "BSD-3-Clause"]
copyleft = "deny"
