# Configuration used for dependency checking with cargo-deny.
#
# For further details on all configuration options see:
# https://embarkstudios.github.io/cargo-deny/checks/cfg.html
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

# Deny all advisories unless explicitly ignored.
[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    # Remove once chrono has been updated to pull in a fixed version of time
    # See https://github.com/chronotope/chrono/issues/553
    "RUSTSEC-2020-0071",
    # atty is not used with a custom global allocator
    "RUSTSEC-2021-0145",
    # xml-rs is Unmaintained (via rusoto_core(0.48))
    "RUSTSEC-2022-0048",
    # rusoto_* is Unmaintained
    # TODO(#416): migrate off rusoto
    "RUSTSEC-2022-0071",
    # ansi_term is Unmaintained (via structopt(0.3.26))
    "RUSTSEC-2021-0139",
]

# Deny multiple versions unless explicitly skipped.
[bans]
multiple-versions = "deny"
wildcards = "allow"

######################################

# Old versions of crates pulled in (transitively) by rusoto_*(v0.47.0)
[[bans.skip]]
name = "hmac"
version = "=0.11.0"

# ed25519-dalek(v1.0.1) => digest(v0.9.x), sha2(v0.9.9)
[[bans.skip]]
name = "digest"
version = "0.9.0"
[[bans.skip]]
name = "sha2"
version = "0.9.9"

# ed25519-dalek(v1.0.1) => rand_core(v0.5.x), {rand(v0.7.3) => getrandom(v0.1.*)}
# tonic(v0.4.0) ..=> rand(v0.8.3) ..=> {rand_core(v0.6.x), getrandom(v0.2.x)}
[[bans.skip]]
name = "getrandom"
version = "0.1.15"
[[bans.skip]]
name = "rand"
version = "0.7.3"
[[bans.skip]]
name = "rand_core"
version = "0.5.1"
[[bans.skip]]
name = "rand_chacha"
version = "0.2.2"

# structopt(0.3.26) => structopt-derive(0.4.18) => heck(0.3.*)
[[bans.skip]]
name = "heck"
version = "0.3.1"

# Various dependencies use windows-sys(0.42.x)
[[bans.skip]]
name = "windows-sys"
version = "0.42.0"

# Various dependencies use block-buffer(0.9.0)
[[bans.skip]]
name = "block-buffer"
version = "0.9.0"

######################################

# List of allowed licenses.
# For more detailed information see http://go/thirdpartylicenses.
[licenses]
allow = [
  "Apache-2.0",
  "ISC",
  "MIT",
  "OpenSSL",
  "BSD-3-Clause",
  "Unicode-DFS-2016",
]
copyleft = "deny"

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 3171872035 }]
