# Configuration used for dependency checking with cargo-deny.
#
# For further details on all configuration options see:
# https://embarkstudios.github.io/cargo-deny/checks/cfg.html
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

# Deny all advisories unless explicitly ignored.
[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
  # TODO: remove when fixed version of rust-traitobject is available.
  "RUSTSEC-2020-0027",
]

# Deny multiple versions unless explicitly skipped.
[bans]
multiple-versions = "deny"
wildcards = "allow"

######################################

# Old versions of crates pulled in (transitively) by rusoto_*(v0.46.0)
[[bans.skip]]
name = "cfg-if"
version = "0.1.10"
[[bans.skip]]
name = "pin-project"
version = "=0.4.26"
[[bans.skip]]
name = "pin-project-internal"
version = "=0.4.26"
[[bans.skip]]
name = "pin-project-lite"
version = "=0.1.10"
[[bans.skip]]
name = "time"
version = "=0.1.44"

# Old versions of crates pulled in (transitively) by google-cloudkms1(v1.0.14)
[[bans.skip]]
name = "base64"
version = "=0.9.3"
[[bans.skip]]
name = "base64"
version = "=0.10.1"
[[bans.skip]]
name = "hyper"
version = "=0.10.16"
[[bans.skip]]
name = "itertools"
version = "=0.8.2"
[[bans.skip]]
name = "log"
version = "=0.3.9"
[[bans.skip]]
name = "percent-encoding"
version = "=1.0.1"
[[bans.skip]]
name = "version_check"
version = "=0.1.5"

# ed25519-dalek(v1.0.1) => rand_core(v0.5.x), {rand(v0.7.3) => getrandom(v0.1.*)}
# tonic(v0.4.0) ..=> rand(v0.8.3) ..=> {rand_core(v0.6.x), getrandom(v0.2.x)}
[[bans.skip]]
name = "getrandom"
version = "0.1.15"
[[bans.skip]]
name = "rand"
version = "0.7.3"
[[bans.skip]]
name = "rand_core"
version = "0.5.1"
[[bans.skip]]
name = "rand_chacha"
version = "0.2.2"

######################################

# List of allowed licenses.
# For more detailed information see http://go/thirdpartylicenses.
[licenses]
allow = [
  "Apache-2.0",
  "MPL-2.0",
  "ISC",
  "MIT",
  "OpenSSL",
  "BSD-3-Clause",
]
copyleft = "deny"

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 3171872035 }]
