[package]
name = "example-keygen"
version = "0.3.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"
license = "Apache-2.0"
publish = false

[dependencies]
tink-core = "^0.3"
tink-daead = "^0.3"
