var N = null;var sourcesIndex = {};
sourcesIndex["example_aead"] = {"name":"","files":["main.rs"]};
sourcesIndex["example_daead"] = {"name":"","files":["main.rs"]};
sourcesIndex["example_keygen"] = {"name":"","files":["main.rs"]};
sourcesIndex["example_kms"] = {"name":"","files":["main.rs"]};
sourcesIndex["example_mac"] = {"name":"","files":["main.rs"]};
sourcesIndex["example_signature"] = {"name":"","files":["main.rs"]};
sourcesIndex["example_streaming"] = {"name":"","files":["main.rs"]};
sourcesIndex["rinkey"] = {"name":"","files":["main.rs"]};
sourcesIndex["tink"] = {"name":"","dirs":[{"name":"codegen","dirs":[{"name":"serde","files":["google.crypto.tink.rs"]}]},{"name":"cryptofmt","files":["mod.rs"]},{"name":"keyset","files":["binary_io.rs","handle.rs","insecure.rs","json_io.rs","manager.rs","mem_io.rs","mod.rs","reader.rs","validation.rs","writer.rs"]},{"name":"primitiveset","files":["mod.rs"]},{"name":"registry","files":["key_manager.rs","key_templates.rs","kms_client.rs","mod.rs"]},{"name":"subtle","files":["hkdf.rs","mod.rs","random.rs"]}],"files":["aead.rs","deterministic_aead.rs","hybrid_decrypt.rs","hybrid_encrypt.rs","lib.rs","mac.rs","prf.rs","signer.rs","streamingaead.rs","utils.rs","verifier.rs"]};
sourcesIndex["tink_aead"] = {"name":"","dirs":[{"name":"subtle","files":["aead.rs","aes_ctr.rs","aes_gcm.rs","aes_gcm_siv.rs","chacha20poly1305.rs","encrypt_then_authenticate.rs","ind_cpa.rs","mod.rs","xchacha20poly1305.rs"]}],"files":["aead_factory.rs","aead_key_templates.rs","aes_ctr_hmac_aead_key_manager.rs","aes_gcm_key_manager.rs","aes_gcm_siv_key_manager.rs","chacha20poly1305_key_manager.rs","kms_envelope_aead.rs","kms_envelope_aead_key_manager.rs","lib.rs","xchacha20poly1305_key_manager.rs"]};
sourcesIndex["tink_awskms"] = {"name":"","files":["aws_kms_aead.rs","aws_kms_client.rs","lib.rs"]};
sourcesIndex["tink_daead"] = {"name":"","files":["aes_siv_key_manager.rs","factory.rs","key_templates.rs","lib.rs","subtle.rs"]};
sourcesIndex["tink_gcpkms"] = {"name":"","files":["gcp_kms_aead.rs","gcp_kms_client.rs","lib.rs"]};
sourcesIndex["tink_mac"] = {"name":"","dirs":[{"name":"subtle","files":["cmac.rs","hmac.rs","mod.rs"]}],"files":["aes_cmac_key_manager.rs","factory.rs","hmac_key_manager.rs","key_templates.rs","lib.rs"]};
sourcesIndex["tink_prf"] = {"name":"","dirs":[{"name":"subtle","files":["aes_cmac.rs","hkdf.rs","hmac.rs","mod.rs"]}],"files":["aes_cmac_prf_key_manager.rs","hkdf_prf_key_manager.rs","hmac_prf_key_manager.rs","key_templates.rs","lib.rs","set_factory.rs"]};
sourcesIndex["tink_signature"] = {"name":"","dirs":[{"name":"subtle","files":["ecdsa_common.rs","ecdsa_signer.rs","ecdsa_verifier.rs","ed25519_signer.rs","ed25519_verifier.rs","mod.rs"]}],"files":["ecdsa_signer_key_manager.rs","ecdsa_verifier_key_manager.rs","ed25519_signer_key_manager.rs","ed25519_verifier_key_manager.rs","lib.rs","proto.rs","signature_key_templates.rs","signer_factory.rs","verifier_factory.rs"]};
sourcesIndex["tink_streaming_aead"] = {"name":"","dirs":[{"name":"subtle","files":["aes_ctr_hmac.rs","aes_gcm_hkdf.rs","mod.rs","noncebased.rs"]}],"files":["aes_ctr_hmac_key_manager.rs","aes_gcm_hkdf_key_manager.rs","decrypt_reader.rs","lib.rs","streamingaead_factory.rs","streamingaead_key_templates.rs"]};
sourcesIndex["tink_testing_server"] = {"name":"","dirs":[{"name":"codegen","files":["tink_testing_api.rs"]}],"files":["aead_service.rs","daead_service.rs","keyset_service.rs","mac_service.rs","main.rs","metadata_service.rs","prf_set_service.rs","signature_service.rs","streaming_service.rs"]};
sourcesIndex["tink_testutil"] = {"name":"","files":["constant.rs","lib.rs","sharedbuf.rs","wycheproofutil.rs"]};
createSourceSidebar();
