[package]
name = "example-prf"
version = "0.2.1"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"
license = "Apache-2.0"
publish = false

[dependencies]
hex = "^0.4.3"
tink-core = "^0.2"
tink-prf = "^0.2"
