[package]
name = "example-kms"
version = "0.2.1"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"
license = "Apache-2.0"
publish = false

[dependencies]
hex = "^0.4.3"
tink-aead = "^0.2"
tink-core = { version = "^0.2", features = ["insecure"] }
tink-awskms = "^0.2"
