[package]
name = "example-kms"
version = "0.1.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
hex = "^0.4.2"
tink = { version = "^0.1", features = ["insecure"] }
tink-aead = "^0.1"
tink-awskms = "^0.1"
