name: crosstest
on:
  push:
    branches:
      - main
      - crosstest
    paths-ignore:
      - README.md

jobs:
  crosstest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - run: git clone --depth 1 --branch v1.6.0 https://github.com/google/tink upstream
      - run: (cd upstream && git apply ../scripts/patches/*)
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: python --version
      - uses: abhinavsingh/setup-bazel@v3
        with:
          version: 3.7.2
      - run: bazel --version
      - run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager "platforms;android-26" --sdk_root=${ANDROID_SDK_ROOT}
      - run: TINK_TESTING_DIR=$PWD/upstream/testing scripts/run-tests.sh
